app:
  name: "Renter Chat API"
  version: "1.0.0"
  environment: "development"

server:
  host: "0.0.0.0"
  port: 8000
  reload: true
  debug: true

logging:
  level: "DEBUG"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    - type: "console"
      level: "DEBUG"
    - type: "file"
      level: "INFO"
      filename: "logs/app.log"
      max_bytes: 10485760  # 10MB
      backup_count: 5

cors:
  allow_origins:
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"
  allow_credentials: true
  allow_methods:
    - "*"
  allow_headers:
    - "*"

llm:
  provider: "claude"  # openai, claude, gemini
  model: "claude-3-5-sonnet-20241022"
  max_tokens: 1024
  temperature: 0.7
  timeout: 30
  # API key is set via CLAUDE_API_KEY environment variable

database:
  type: "sqlite"
  url: "sqlite:///./renter_chat_dev.db"
  echo: true

observability:
  enable_request_logging: true
  log_llm_usage: true
  log_tool_calls: true